// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "button": {
      name: "button",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/button.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/button.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dialog": {
      name: "dialog",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/dialog.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/dialog.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "input": {
      name: "input",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/input.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/input.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "kbd": {
      name: "kbd",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/kbd.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/kbd.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "number-input": {
      name: "number-input",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/number-input.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/number-input.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dropdown-menu": {
      name: "dropdown-menu",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/dropdown-menu.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/dropdown-menu.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "accordion": {
      name: "accordion",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/accordion.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/accordion.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "checkbox": {
      name: "checkbox",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/checkbox.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/checkbox.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "tabs": {
      name: "tabs",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/tabs.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/tabs.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "avatar": {
      name: "avatar",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/avatar.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/avatar.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "tooltip": {
      name: "tooltip",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/tooltip.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/tooltip.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "select": {
      name: "select",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/select.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/select.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toggle": {
      name: "toggle",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/toggle.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/toggle.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-demo": {
      name: "button-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-destructive": {
      name: "button-destructive",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-destructive.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-destructive.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-ghost": {
      name: "button-ghost",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-ghost.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-ghost.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-icon": {
      name: "button-icon",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-icon.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-icon.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-link": {
      name: "button-link",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-link.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-link.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-loading": {
      name: "button-loading",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-loading.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-loading.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-outline": {
      name: "button-outline",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-outline.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-outline.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-secondary": {
      name: "button-secondary",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-secondary.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-secondary.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dialog-demo": {
      name: "dialog-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["dialog"],
      files: [{
        path: "registry/default/examples/dialog-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/dialog-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dialog-custom-close-button": {
      name: "dialog-custom-close-button",
      description: "",
      type: "registry:example",
      registryDependencies: ["dialog"],
      files: [{
        path: "registry/default/examples/dialog-custom-close-button.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/dialog-custom-close-button.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dialog-with-no-x-button": {
      name: "dialog-with-no-x-button",
      description: "",
      type: "registry:example",
      registryDependencies: ["dialog"],
      files: [{
        path: "registry/default/examples/dialog-with-no-x-button.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/dialog-with-no-x-button.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dialog-nested": {
      name: "dialog-nested",
      description: "",
      type: "registry:example",
      registryDependencies: ["dialog"],
      files: [{
        path: "registry/default/examples/dialog-nested.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/dialog-nested.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "input-demo": {
      name: "input-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["input"],
      files: [{
        path: "registry/default/examples/input-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/input-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "input-with-label": {
      name: "input-with-label",
      description: "",
      type: "registry:example",
      registryDependencies: ["input"],
      files: [{
        path: "registry/default/examples/input-with-label.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/input-with-label.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "input-with-floating-label": {
      name: "input-with-floating-label",
      description: "",
      type: "registry:example",
      registryDependencies: ["input"],
      files: [{
        path: "registry/default/examples/input-with-floating-label.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/input-with-floating-label.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "input-secondary": {
      name: "input-secondary",
      description: "",
      type: "registry:example",
      registryDependencies: ["input"],
      files: [{
        path: "registry/default/examples/input-secondary.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/input-secondary.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "input-disabled": {
      name: "input-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: ["input"],
      files: [{
        path: "registry/default/examples/input-disabled.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/input-disabled.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "kbd-demo": {
      name: "kbd-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["kbd"],
      files: [{
        path: "registry/default/examples/kbd-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/kbd-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "kbd-outline": {
      name: "kbd-outline",
      description: "",
      type: "registry:example",
      registryDependencies: ["input"],
      files: [{
        path: "registry/default/examples/kbd-outline.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/kbd-outline.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "kbd-ghost": {
      name: "kbd-ghost",
      description: "",
      type: "registry:example",
      registryDependencies: ["kbd"],
      files: [{
        path: "registry/default/examples/kbd-ghost.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/kbd-ghost.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "number-input-demo": {
      name: "number-input-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["number-input"],
      files: [{
        path: "registry/default/examples/number-input-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/number-input-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "number-input-min-max": {
      name: "number-input-min-max",
      description: "",
      type: "registry:example",
      registryDependencies: ["number-input"],
      files: [{
        path: "registry/default/examples/number-input-min-max.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/number-input-min-max.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "number-input-disabled": {
      name: "number-input-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: ["number-input"],
      files: [{
        path: "registry/default/examples/number-input-disabled.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/number-input-disabled.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "number-input-scrub-direction": {
      name: "number-input-scrub-direction",
      description: "",
      type: "registry:example",
      registryDependencies: ["number-input"],
      files: [{
        path: "registry/default/examples/number-input-scrub-direction.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/number-input-scrub-direction.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dropdown-menu-demo": {
      name: "dropdown-menu-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["dropdown-menu"],
      files: [{
        path: "registry/default/examples/dropdown-menu-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/dropdown-menu-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dropdown-menu-radio": {
      name: "dropdown-menu-radio",
      description: "",
      type: "registry:example",
      registryDependencies: ["dropdown-menu"],
      files: [{
        path: "registry/default/examples/dropdown-menu-radio.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/dropdown-menu-radio.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dropdown-menu-checkbox": {
      name: "dropdown-menu-checkbox",
      description: "",
      type: "registry:example",
      registryDependencies: ["dropdown-menu"],
      files: [{
        path: "registry/default/examples/dropdown-menu-checkbox.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/dropdown-menu-checkbox.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dropdown-menu-hover": {
      name: "dropdown-menu-hover",
      description: "",
      type: "registry:example",
      registryDependencies: ["dropdown-menu"],
      files: [{
        path: "registry/default/examples/dropdown-menu-hover.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/dropdown-menu-hover.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "accordion-demo": {
      name: "accordion-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["accordion"],
      files: [{
        path: "registry/default/examples/accordion-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/accordion-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "accordion-disabled": {
      name: "accordion-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: ["accordion"],
      files: [{
        path: "registry/default/examples/accordion-disabled.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/accordion-disabled.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "accordion-single": {
      name: "accordion-single",
      description: "",
      type: "registry:example",
      registryDependencies: ["accordion"],
      files: [{
        path: "registry/default/examples/accordion-single.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/accordion-single.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "checkbox-demo": {
      name: "checkbox-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["accordion"],
      files: [{
        path: "registry/default/examples/checkbox-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/checkbox-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "checkbox-disabled": {
      name: "checkbox-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: ["accordion"],
      files: [{
        path: "registry/default/examples/checkbox-disabled.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/checkbox-disabled.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "tabs-demo": {
      name: "tabs-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["tabs"],
      files: [{
        path: "registry/default/examples/tabs-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/tabs-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "tabs-vertical": {
      name: "tabs-vertical",
      description: "",
      type: "registry:example",
      registryDependencies: ["tabs"],
      files: [{
        path: "registry/default/examples/tabs-vertical.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/tabs-vertical.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "avatar-demo": {
      name: "avatar-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["avatar"],
      files: [{
        path: "registry/default/examples/avatar-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/avatar-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "select-demo": {
      name: "select-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["select"],
      files: [{
        path: "registry/default/examples/select-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/select-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "select-with-group": {
      name: "select-with-group",
      description: "",
      type: "registry:example",
      registryDependencies: ["select"],
      files: [{
        path: "registry/default/examples/select-with-group.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/select-with-group.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "select-align-trigger": {
      name: "select-align-trigger",
      description: "",
      type: "registry:example",
      registryDependencies: ["select"],
      files: [{
        path: "registry/default/examples/select-align-trigger.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/select-align-trigger.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "tooltip-demo": {
      name: "tooltip-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["tooltip"],
      files: [{
        path: "registry/default/examples/tooltip-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/tooltip-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toggle-demo": {
      name: "toggle-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle"],
      files: [{
        path: "registry/default/examples/toggle-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toggle-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toggle-outline": {
      name: "toggle-outline",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle"],
      files: [{
        path: "registry/default/examples/toggle-outline.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toggle-outline.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toggle-disabled": {
      name: "toggle-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle"],
      files: [{
        path: "registry/default/examples/toggle-disabled.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toggle-disabled.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toggle-large": {
      name: "toggle-large",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle"],
      files: [{
        path: "registry/default/examples/toggle-large.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toggle-large.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toggle-small": {
      name: "toggle-small",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle"],
      files: [{
        path: "registry/default/examples/toggle-small.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toggle-small.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "mode-toggle": {
      name: "mode-toggle",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/mode-toggle.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/mode-toggle.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
  },
}
