// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "button": {
      name: "button",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/button.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/button.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dialog": {
      name: "dialog",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/dialog.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/dialog.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-demo": {
      name: "button-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-as-child": {
      name: "button-as-child",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-as-child.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-as-child.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-destructive": {
      name: "button-destructive",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-destructive.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-destructive.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-ghost": {
      name: "button-ghost",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-ghost.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-ghost.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-icon": {
      name: "button-icon",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-icon.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-icon.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-link": {
      name: "button-link",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-link.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-link.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-loading": {
      name: "button-loading",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-loading.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-loading.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-outline": {
      name: "button-outline",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-outline.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-outline.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-secondary": {
      name: "button-secondary",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/examples/button-secondary.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-secondary.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dialog-demo": {
      name: "dialog-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["dialog"],
      files: [{
        path: "registry/default/examples/dialog-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/dialog-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dialog-with-close-button": {
      name: "dialog-with-close-button",
      description: "",
      type: "registry:example",
      registryDependencies: ["dialog"],
      files: [{
        path: "registry/default/examples/dialog-with-close-button.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/dialog-with-close-button.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dialog-with-no-x-button": {
      name: "dialog-with-no-x-button",
      description: "",
      type: "registry:example",
      registryDependencies: ["dialog"],
      files: [{
        path: "registry/default/examples/dialog-with-no-x-button.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/dialog-with-no-x-button.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
  },
}
